### ISSUE TITLE
Unable to view requester Statistics

### ISSUE THREAD

**Issue by Ashraf09** [cloudyr/MTurkR#118]
Hi,

I am facing below error while trying to see requester statustics:

Error (AWS.MechanicalTurk.InvalidParameterValue):
  The value "NumberAssignmentsAvailable" is not valid for the parameter Statistic. This statistic is no longer supported.. (1489004386534)
Error in `[<-.data.frame`(`*tmp*`, i, 2, value = structure(list(Date = logical(0),  : 
  replacement has length zero
In addition: Warning messages:
1: In GetStatistic(statistics[i], period = period, ...) : Invalid Request
2: In `[<-.data.frame`(`*tmp*`, i, 2, value = list(Date = logical(0),  :
  provided 3 variables to replace 1 variables

**Comment by leeper** [comment]
Are you using the most recent version of MTurkR (0.8.0)? This has been removed, so you likely just have an outdated version of the package.
