### ISSUE TITLE
Issue with GetBonuses

### ISSUE THREAD

**Issue by esp2572** [cloudyr/MTurkR#123]
GetBonuses for a specific HIT ID is recently giving me the following error

"Error in runningtotal + batch_total : 
  non-numeric argument to binary operator"

It was working just fine a few days ago, and I have made no changes to the code. 
This is only occurring for this specific HIT ID, it also works just fine for other HIT ID's.
I suspect it might be something on mTurk's end but any help would be appreciated.

Thanks!

**Comment by esp2572** [comment]
Nevermind, I figured it out myself.

**Comment by leeper** [comment]
What was the problem?

**Comment by esp2572** [comment]
We ended up bonusing over 100 workers and if I understand correctly, the command can only retrieve 100 bonuses per page. I figured out that I needed to add pagenumber parameters and set return.all to false like so...

GetBonuses(hit = "_HIT ID OMITTED_", pagenumber = "1", return.all = FALSE)

We anticipate bonusing several hundred workers for this HIT, is there any way to retrieve more than 100 bonuses at a time? Could this feature be implemented?

Thank you for your time!

**Comment by leeper** [comment]
It should work with `return.all = TRUE`. If not, there's a bug.

**Comment by esp2572** [comment]
By "should work" do you mean it should be retrieving >100 bonuses at a time or is that still a limitation?

If it is helpful... 

GetBonuses(hit = "_HIT ID OMITTED_", pagenumber = "2", return.all = TRUE) works and retrieves bonuses past the first 100 but....
GetBonuses(hit = "_HIT ID OMITTED_", pagenumber = "1", return.all = TRUE) does not, and displays the error:
"Error in runningtotal + batch_total :
non-numeric argument to binary operator"

**Comment by leeper** [comment]
Should work meaning it should return all of them if `return.all = TRUE`. So yea, that's a bug.
