### ISSUE TITLE
Maintainer?

### ISSUE THREAD

**Issue by missaugustina** [cloudyr/MTurkR#129]
I saw on Twitter you were looking for package maintainers. I'm not sure if this was one of the ones you needed help with?

**Comment by leeper** [comment]
If you're interested, sure! It's super stable, so shouldn't be much work at all.

**Comment by missaugustina** [comment]
Sorry for the delay, I was backlogged with some day job things! I'll be catching up on this this week.

**Comment by missaugustina** [comment]
PS. I'm running a workshop tonight to teach people how to work together on Github & planning to use these repos as potential examples, so maybe we'll see some activity! If anyone accidentally creates a bogus issue, I'll take care of it.

**Comment by leeper** [comment]
Great! Thanks so much for taking this over!

**Comment by missaugustina** [comment]
Hey sorry I've been MIA, just wrapping up some work things before the year end & I should be able to start focusing on this next week!

**Comment by leeper** [comment]
Hey @missaugustina, given https://github.com/cloudyr/MTurkR/issues/131, I’m going to pull this package from CRAN since it’s no longer going to work. Looks like you won’t need to take over after all. Really appreciate you volunteering to do so though!
